server:
  port: 9100

app-config:
  oauth:
    jwt-secret: d11714514a6d45b917d87aebd5f14f31f71c4f6f40a60022c2480b0ac4840ea5

  cep:
    url: https://viacep.com.br/ws/%d/json/

spring:
  application:
    name: gestao-mercados-api

  flyway:
    enabled: true
    out-of-order: true
    baseline-on-migrate: true

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

logging:
  level:
    org:
      springframework:
        security: DEBUG
        security.authentication: DEBUG
        security.web.access: DEBUG